### ISSUE TITLE
feat: add nested grouping and accordion functionality in table component.

### ISSUE THREAD

**Issue by gmukul01** [medly/medly-components#113]
### In Scope
- Nested row selection
- Nested row accordion

https://www.figma.com/file/vA4EQdxl0d0ETtYpw2uSjW/Medly-Pattern-Library-B2B-Internal?node-id=7343%3A1201

**Comment by swanandvk** [comment]
@gmukul01 does this allow to have nested table/multiple child rows inside individual cell ? 
eg: cell column to support array type for rendering multiple table rows inside a cell
