### ISSUE TITLE
feat: masking on text input

### ISSUE THREAD

**Issue by vitulrana** [medly/medly-components#127]
### Description
Feature Input Masking is mostly related to Credit Cards and Phone Numbers. For Example -

US Phone Numbers are added displayed in **123-456-7891** or **(123) 456-7891**. Its easy to format number when you are dispalying but Medly UI Mockups suggests to have Text Inputs have this type of Masking also.

Same Case is with Credit Cards **4444-4444-4444-4444**

### Solution you'd like
Text Input having Props maskPattern where you can define Pattern like above and then Input will consider it automatically.

### Alternatives you've considered
I tried an alternative where we override the **event.target.value** using onInputChange function by the help of a Regex like **(\d{3})(\d{3})(\d{4})**

But its a very bad solution to override event.target.value on every input change.

### Additional context
Need something like this => https://www.npmjs.com/package/react-input-mask

**Comment by gmukul01** [comment]
Fixed this
