### ISSUE TITLE
bug: Datepicker should not show error message when value already present 

### ISSUE THREAD

**Issue by shabbir-sj** [medly/medly-components#198]
### Describe the bug
With required property true, while selecting date from datePicker calendar at the first time, error message will be appeared even if value is there.

### To Reproduce
1. Open datePicker's calendar via calendar icon.
2. select any date
3. Error message will be there.

### Expected behavior
Error message should not be displayed if user selecting value via calendar.

### Package / Module
 - @medly-components/core => DatePicker

**Comment by gmukul01** [comment]
fixed in PR: 166
