### ISSUE TITLE
feat: Function to be called after both the dates are selected

### ISSUE THREAD

**Issue by wsameer** [medly/medly-components#228]
### Description
Currently, the date range picker stays open even when both start and end dates are selected. There is no way to know when both start and end dates are selected. The front-end needs a way to know when the user has finished selecting the date-ranges. 

### Solution you'd like
A prop which takes a function (A) as a parameter and calls A when both the start and end dates are selected on the calendar.

### Alternatives you've considered
The `<DateRangePicker>` component can call the `onChange` prop only when both start and end dates are selected. Currently, the `onChange` props is called on every date selection.

**Comment by Tajwinder** [comment]
Hi Sameer, I would like to work on this issue. Please assign it to me.
