### ISSUE TITLE
bug: MultiSelect shows value instead of label as the display value in input field

### ISSUE THREAD

**Issue by kooskoos20** [medly/medly-components#287]
### Describe the bug
`MultiSelect` component shows value instead of label as the display value in input when options are selected. It results in a problem with internal values being exposed in the input fields.

### To Reproduce

1. Use `MultiSelect` component with different values for label and value fields in options.
2. Select any option.
3. Check display value in input field.
4. It will show value as display value instead of label.

### Expected behavior
The input display value after selecting any option should be label and not value.

### Screenshots
- Options provided to `MultiSelect`
![image](https://user-images.githubusercontent.com/42716396/119949387-74892f00-bfb7-11eb-9c99-7db8aa09928e.png)

- Notice label starts with capital 'L' in **Lorem Pharmacy**
![image](https://user-images.githubusercontent.com/42716396/119948961-004e8b80-bfb7-11eb-8e9b-b25f48109542.png)

- Though the input display values show selected option **Lorem Pharmacy** with small 'l' which is the value field **lorem pharmacy**
![image](https://user-images.githubusercontent.com/42716396/119949293-5de2d800-bfb7-11eb-9c32-0267b79295fc.png)

### Package versions
 - @medly-components/core : 1.46.13
 - @medly-components/forms : 1.19.3
 - @medly-components/icons : 1.5.15
 - @medly-components/layout : 1.20.13
 - @medly-components/loaders : 1.0.53
 - @medly-components/theme : 1.30.8
 - @medly-components/utils : 1.8.15

**Comment by jaredgiangrasso** [comment]
@kooskoos20 Fixed in #288
