### ISSUE TITLE
feat: Multi select component to have creatable options

### ISSUE THREAD

**Issue by abhishekashyap** [medly/medly-components#289]
### Description
Ability to create new options along with choosing existing options in multi select component

### Solution you'd like
In multi select component we have to provide pre defined options. But if we want to add our custom option on-the-fly there is no way to do it.

### Alternatives you've considered
[React-select](https://react-select.com/creatable) has a creatable component that can be used to achieve the same effect

### Additional context
Example: How Trello handles tags

**Comment by TaneliR** [comment]
I could try to solve this 🤔 I guess you prefer no added dependencies?
