### ISSUE TITLE
feat: make background color of tabs to transparent for flat variant

### ISSUE THREAD

**Issue by wsameer** [medly/medly-components#452]
### Description
The Tabs component inside the Core package accepts a `variant` prop.
As a user, I want the background color of the tab headers to be transparent when the value of `variant` is `flat`.
Currently, the background color is white.

![image](https://user-images.githubusercontent.com/8468992/134894381-93c1fbd4-de61-4b2d-8fbe-68ba1b387199.png)

### Solution you'd like
Change the background color style to transparent when the value of `variant` is `flat`.

**Comment by PulkitBanta** [comment]
Hi Sameer, I would like to work on this issue. Please assign it to me.

**Comment by wsameer** [comment]
All yours @PulkitBanta :)
