### ISSUE TITLE
feat: add Prefix support in multiSelect component

### ISSUE THREAD

**Issue by wsameer** [medly/medly-components#462]
### Description
The current `MultiSelect` component does not support the feature of adding a prefix.
We would like the `MultiSelect` component to provide a way to add an icon OR text as a prefix.

### Solution you'd like

- A new prop called `prefix` which accepts a `React.FC<any>` as a value and displays the same as a prefix in the `MultiSelect` component on the UI.
- The `prefix` prop should be optional.
- The component passed in the `prefix` prop should take the color of the label.
- The `prefix` component should leave a `1.6rem` margin on its right side.
- The `prefix` component should be displayed vertically in the center.

### Additional context
This feature has already been added as a part of the `SingleSelect` component.

![image](https://user-images.githubusercontent.com/8468992/135224344-a0ea3f4f-3cc3-4dfe-9345-9d07319c159d.png)

**Comment by binkpitch** [comment]
Hi, I would like to work on this issue. Can you assign it to me?

**Comment by wsameer** [comment]
> Hi, I would like to work on this issue. Can you assign it to me?

@binkpitch  sure. All yours :)
