### ISSUE TITLE
bug: character count not visible in `TextField`

### ISSUE THREAD

**Issue by PulkitBanta** [medly/medly-components#499]
### Describe the bug
Enabling `character count` on TextField does not show character count in UI.

### To Reproduce

1. Go to [TextField](https://www.medlycomponents.com/?path=/story/core--text-field)
2. Click on Character Count in Knobs
3. Enter some text in text field.
4. Character Count is not visible.

### Expected behavior
Character count must be visible on the UI.

### Video

https://user-images.githubusercontent.com/43134750/138833620-8297687a-de22-4597-b969-4969096f47e1.mov

**Comment by abhishekashyap** [comment]
Resolved in #514
