### ISSUE TITLE
enhancement: multi-select remove dependency

### ISSUE THREAD

**Issue by PulkitBanta** [medly/medly-components#577]
### Describe the issue

When `showDecorators` is `false` it hides the **number of selections** as well as the **dropdown icon (chevron icon)**. 
Hiding the chevron icon doesn’t seems a good UX. Apart from that it also hides the prefix passed but prefix is already optional and if someone doesn’t want to show it can be rendered conditionally.

##### When `showDecorators` is `false`

- Do not hide chevron icon
- Do not hide prefix
- Only hide number of selections

### Solution you'd like

- Remove conditional rendering of `chevron icon` and `prefix`

**Comment by gmukul01** [comment]
You can simply achieve this specific scenario by overriding the CSS.
