### ISSUE TITLE
feat: [Table Component] Ability to reduce size of row selection checkbox

### ISSUE THREAD

**Issue by kdabir** [medly/medly-components#663]
### Description
User is not able to resize the column that is selectable checkbox. Also we cannot provide the `fraction`  value  for this column keeping it too wide in some cases.

<img width="210" alt="image" src="https://user-images.githubusercontent.com/735240/168973000-3b1f7e40-ddbf-49f2-a16d-b9c4cb5cefe0.png">

### Solution you'd like
either let uses resize the column or (better) support setting the width in fraction for this column.

**Comment by PulkitBanta** [comment]
@kdabir do you see any use case where user will like to expand this column? And for reducing the size, there was some issue in previous version where it was expanding and taking nearly `1fr` (fraction) of size. Can you try to upgrade the `medly-components` in your application and check if you still need this feature?

**Comment by kdabir** [comment]
user will never want to expand, however may want to reduce the size if it's too wide. I have seen this issue intermittently (i.e. it's not always this wide). If it's already fixed then there no need to give option/resize.
